name: image_form_field
description: Upload images in Flutter forms
version: 0.1.0
homepage: https://github.com/tshedor/flutter_image_form_field

environment:
  sdk: '>=1.20.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+2
  multi_image_picker: ^4.8.1
  photo_view: ^0.13.0
