name: image_form_field
description: Upload images in Flutter forms
version: 1.0.0-nullsafety.0
homepage: https://github.com/tshedor/flutter_image_form_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.7.2
